const users = [
  {
    id: 1,
    name: 'Emma',
    age: 25,
    gender: 'Female',
    location: 'Los Angeles',
    bio: 'Adventurous soul!',
    image: 'https://images.pexels.com/photos/7477662/pexels-photo-7477662.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    checkMatch: false,
  },
  {
    id: 2,
    name: 'Sophia',
    age: 21,
    gender: 'Female',
    location: 'Miami',
    bio: 'Looking for partner!',
    image: 'https://images.pexels.com/photos/19113514/pexels-photo-19113514/free-photo-of-bride-in-sensual-pose-with-eyes-closed.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    checkMatch: false,
  },
  {
    id: 3,
    name: 'Olivia',
    age: 25,
    gender: 'Female',
    location: 'San Francisco',
    bio: 'Let’s create our own story!',
    image: 'https://images.pexels.com/photos/904117/pexels-photo-904117.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 4,
    name: 'Ava',
    age: 25,
    gender: 'Female',
    location: 'New York',
    bio: 'Dreamer and achiever!',
    image: 'https://images.pexels.com/photos/1839963/pexels-photo-1839963.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: true,
  },
  {
    id: 5,
    name: 'Isabella',
    age: 25,
    gender: 'Female',
    location: 'Chicago',
    bio: 'Passionate foodie',
    image: 'https://images.pexels.com/photos/1689731/pexels-photo-1689731.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 6,
    name: 'Sophie',
    age: 25,
    gender: 'Female',
    location: 'Seattle',
    bio: 'Enjoys a good book!',
    image: 'https://images.pexels.com/photos/1844012/pexels-photo-1844012.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 7,
    name: 'Chloe',
    age: 25,
    gender: 'Female',
    location: 'Austin',
    bio: 'Music enthusiast',
   image: 'https://images.pexels.com/photos/3679044/pexels-photo-3679044.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 8,
    name: 'alexa',
    age: 25,
    gender: 'Female',
    location: 'jaipur',
    bio: 'Music enthusiast',
    image: 'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 9,
    name: 'faukli',
    age: 25,
    gender: 'Female',
    location: 'usa',
    bio: 'Music enthusiast',
   image: 'https://images.pexels.com/photos/1107971/pexels-photo-1107971.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
  {
    id: 10,
    name: 'jensi',
    age: 25,
    gender: 'Female',
    location: 'washington',
    bio: 'Music enthusiast',
   image: 'https://images.pexels.com/photos/3679044/pexels-photo-3679044.jpeg?auto=compress&cs=tinysrgb&w=600',
    checkMatch: false,
  },
];

export default users;
